import { RouteInterface } from 'App/Interfaces/RouteInterface'

export const swaggerMock: RouteInterface[] = [
  {
    id: 0,
    name: 'sentryEvents',
    endpoint: 'events/subscribe',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"id":86672}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"jwylFoSkRCGDw","description":"EphznGebgINB","details":["MhwkKgIvp"]}}',
        name: 'Bad Request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 401,
        body: '{"error":{"code":"Sxht","description":"dJNmOsrho","details":["tGrU"]}}',
        name: 'Unauthorized',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 403,
        body: '{"error":{"code":"FWJ","description":"IbkdYrTU","details":["PncuFmmN"]}}',
        name: 'Forbidden',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"DfeLgkKGJSsRlHQ","description":"pmNHHqJScb","details":["MxBNicjKN"]}}',
        name: 'Not Found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"tPRUJTRaem","description":"qFifrrE","details":["rwJPRFbTQTr"]}}',
        name: 'Internal Server Error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getProductWithMerca',
    endpoint: 'stores/products/product',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"id":74692,"codMerca":28271,"order":83427,"parentId":61837,"sectionId":72267,"imageUrl":"vfdNjCbEUe","name":"RuyrIONH","isVisible":true,"pvp":0.27,"regularPvp":0.67,"saleUnitOfMeasure":"QeY","saleUnitOfMeasureFormat":"Zps","commercialDescription":"hh","regionalDescription":"iftxIlqcdz","tare":30678,"regularTare":33253,"stockQuantity":0.37,"status":"CLEARED"}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"xNkGfALuv","description":"zWQY","details":["AcMzYStwq"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"yuvNdQQGcw","description":"iIDYcApP","details":["NiAYdDjNNrJhf"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"VeRWGQHCN","description":"nNnsJTBW","details":["toXh"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'updateProduct',
    endpoint: 'stores/products/product',
    method: 'put',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"id":56710,"codMerca":5817,"order":83719,"parentId":24580,"sectionId":71296,"imageUrl":"zX","name":"XXo","isVisible":false,"pvp":0.05,"regularPvp":0.02,"saleUnitOfMeasure":"vld","saleUnitOfMeasureFormat":"Dv","commercialDescription":"bjJbDjEch","regionalDescription":"oEHRIki","tare":56408,"regularTare":84566,"stockQuantity":0.22,"status":"LOCKED"}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"iOxKbmmZfGhJw","description":"TRaxp","details":["QMLoZoT"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"oNEMmkzPgq","description":"Omu","details":["Zv"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"VMdzFuIVP","description":"iaHDqEOtkroIH","details":["F"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'sendProductToScale',
    endpoint: 'stores/products/product/send',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 204,
        body: '""',
        name: 'Product sent successfully to the driver.',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"yyJg","description":"avlZZim","details":["UmvzjuRxCMj"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"zModjAED","description":"yjBibEq","details":["HFYZTDMmnECDyd"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"MVb","description":"swj","details":["WruYm"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getProductsCollection',
    endpoint: 'stores/products/structure/{param}/type/{param}',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"pagination":{"requestedPage":63566,"requestedSize":39034,"retrievedResults":1891,"totalResults":60401,"nextPage":"YaknpLMY","previousPage":"qaB"},"changes":[{"id":43394,"codMerca":51116,"order":92661,"parentId":10175,"sectionId":9695,"imageUrl":"KttGxvdGAjBkW","name":"njXqh","isVisible":true,"pvp":0.03,"regularPvp":0.89,"saleUnitOfMeasure":"DjQzqnOOMfsp","saleUnitOfMeasureFormat":"U","commercialDescription":"PKxnQoaMccyZrYF","regionalDescription":"HYyNP","tare":26163,"regularTare":14681,"stockQuantity":0.15,"status":"LOCKED"}]}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"kAQ","description":"ItVCOpHNS","details":["LXXmDqutNt"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"UBRVQafTjPCZJ","description":"nMEBoOgRKlZER","details":["CqkXZxl"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"xfMKoT","description":"njtUtgWjGj","details":["QAROXv"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getScaleStructureBreakageProducts',
    endpoint: 'stores/products/structure/{param}/breakages',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '[{"imageUrl":"kePRIwwn","codMerca":93168,"description":"N"}]',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"NoGQF","description":"VRNUCD","details":["XmM"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"rXH","description":"tAGyAgCdS","details":["uD"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"ehDCc","description":"YDBPDlvJSHG","details":["tNBsro"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'createProductBreakage',
    endpoint: 'stores/products/breakages/sites/{param}',
    method: 'post',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 202,
        body: '""',
        name: 'Request accepted for processing',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"XFWVuNOVrGhi","description":"pvECjiZ","details":["HDXhL"]}}',
        name: 'Bad Request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 401,
        body: '{"error":{"code":"wr","description":"NvYBuBzSpVeYWz","details":["rNPcJ"]}}',
        name: 'Unauthorized',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 403,
        body: '{"error":{"code":"viaScJt","description":"AuzkYhUgbukBd","details":["MbtROokmQlVPFdJ"]}}',
        name: 'Forbidden',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"UpcPOvqGON","description":"pxB","details":["qmpFKJm"]}}',
        name: 'Not Found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"cTqlWIvGTQFLW","description":"fpAodGk","details":["oUYxNkDdJQp"]}}',
        name: 'Internal Server Error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getProductBreakageReasons',
    endpoint: 'stores/products/breakages/reasons',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '[{"id":"ctEsoUFztDxNsM","motiveId":19401,"submotiveId":68869,"description":"del"}]',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"ZSEjN","description":"kXyNuVKL","details":["OQEu"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"UZzjpzdDFBGy","description":"YAa","details":["VJglFiu"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"OctVBiODQQocZy","description":"yBmIJoCSfNO","details":["TGiluCikPPt"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getConfiguration',
    endpoint: 'configuration',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"path":"ihWZsKjeY","images":[{"code":"rZjIcc","imageUrl":"gHHvXRbnr"}],"locale":"OdjUJepBCft"}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"BJQPQSJRrar","description":"QnpwW","details":["HEP"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"YvREgWZGu","description":"vm","details":["vWFu"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"kvLqtdYBVnfF","description":"yvWW","details":["HCNZg"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getScaleStructure',
    endpoint: 'scale/structure',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '[{"id":9653,"order":63105,"imageUrl":"SjJCarbUSh","name":"LcByj","sections":[{"id":60807,"order":42142,"name":"ke","code":"LABEL INGREDIENTS"}],"isVisible":true}]',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"yJzxA","description":"uQgNBRNQ","details":["gGFXtj"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"tgA","description":"zDeBjSCOU","details":["Uw"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"oCZi","description":"jsYhgssPItk","details":["ZkF"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'pair',
    endpoint: 'scalehandler/pair',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'false',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"qIG","description":"NIpOOlkIxOk","details":["KswJzcgqko"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"mdHApAsSSfqf","description":"IqXTcqDLnaWECB","details":["eiqQLaHFGxnt"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"WuROHkuDoO","description":"j","details":["dXziqpOVf"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'setEnable',
    endpoint: 'scalehandler/enable',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'true',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"iQ","description":"BKh","details":["nAggkeMzFuBNtYl"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"lDnDrALhAbiT","description":"NdcJ","details":["lyr"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"DYSSZR","description":"bNDmFh","details":["DBH"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'sendProduct',
    endpoint: 'scalehandler/sendproduct',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'true',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"V","description":"VuDsdD","details":["xHhSPNtGr"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"GMjpzzulKvLlPle","description":"uuFABuQJe","details":["VDu"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"tmTPBZytRtwVsu","description":"VZriynllIA","details":["PHZqavIVGg"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'recoverSalesUnitOfMeasure',
    endpoint: 'scalehandler/product/recover/unit',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'true',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"MlnD","description":"l","details":["ILHTNLGUF"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"TwAO","description":"CQ","details":["yxSlD"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"imSslArKM","description":"GIrVBXkVwmIX","details":["CVeMdYDWJm"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'recoverWeight',
    endpoint: 'scalehandler/product/recover/weight',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '0.18',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"krb","description":"HaItBqbbhNVUQGy","details":["YSUbKSzZZAsp"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"CYamJS","description":"pBrWEStrhUX","details":["YJvCvEtZbrSioi"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"usaYFcu","description":"pAgsGmSNJhP","details":["XqkA"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'resetProduct',
    endpoint: 'scalehandler/resetproduct',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'false',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"hkmhmQpl","description":"YZBnsVBhnNTsqb","details":["H"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"oEyLglblYYR","description":"navAY","details":["F"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"qYjZpJozpvLssZ","description":"BlNdXKQk","details":["oGI"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'resetMode',
    endpoint: 'scalehandler/resetmode',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'false',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"GiTlnndmiMTvrZ","description":"U","details":["VK"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"RUidGolD","description":"dMcLa","details":["CjYKnlZGL"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"wKh","description":"mpEUZwgrKbRfmpN","details":["DnF"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'close',
    endpoint: 'scalehandler/close',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'true',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"DeXDDmAf","description":"vg","details":["YmZLTazVlJwf"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"Np","description":"rPFFPOWuY","details":["NLiNDBDpY"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"zdZMRUWRsICf","description":"CWsXzGAbTnGOJgg","details":["JOwtVMRrU"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'closeScale',
    endpoint: 'scalehandler/exit',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 204,
        body: '""',
        name: 'Close scale successfully.',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"DDIMQv","description":"OtpYTYGBqw","details":["bYjYe"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"lD","description":"GEirwWKL","details":["hGAHDTfYBIKump"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"thWONoB","description":"zYqS","details":["gQBiAHk"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'calibrateScale',
    endpoint: 'scalehandler/calibrate',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'false',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"KUwaOUJl","description":"cIr","details":["oyotbxugiB"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"Xkw","description":"pLKxnz","details":["EnmvMQqeYK"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"ywEuWzfGmvivrjW","description":"QUfcWbLjoFpn","details":["cPOMdXaeDA"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'testAndAdjustment',
    endpoint: 'scalehandler/test/adjustment',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'false',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"ikZpZaAfaWzWGLB","description":"EbRsX","details":["wgGxRzMfMUYg"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"v","description":"sULRYAWrzGiT","details":["jSvbLI"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"rMlVOPJ","description":"VwttKEu","details":["lMixR"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'openTicket',
    endpoint: 'scalehandler/open/ticket',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: 'false',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"dwiljHE","description":"HqgL","details":["dnxyy"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"HS","description":"i","details":["VxTbdeZD"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"MvtEizueVPmR","description":"OZHduWKMDwUmZ","details":["mOBwySLJg"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'recoverDisplayWeight',
    endpoint: 'scalehandler/read/weight',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '0.45',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"lPLuUmxIC","description":"OSAIZxkfGXX","details":["hmZa"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"CqP","description":"nTGmqbSWmzqQ","details":["R"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"zTjXAlalO","description":"HPTQBrnpoGYG","details":["NEUQCNoym"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'createTransaction',
    endpoint: 'labels/transaction',
    method: 'post',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 201,
        body: '{"transactionId":62852,"created":"voLZ","last_update":"MQBnsiS","status":53444,"type":63377,"description":"TsvrBFsshMaNvGz"}',
        name: 'Transaction created successfully',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"M","description":"bdQuceZqU","details":["KYGHiWM"]}}',
        name: 'Bad Request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 401,
        body: '{"error":{"code":"ZJjzhspKmy","description":"nuyXogocWtQW","details":["sClLxiSC"]}}',
        name: 'Unauthorized',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 403,
        body: '{"error":{"code":"CnDvjx","description":"gSjS","details":["CHbhuFRjPzWoe"]}}',
        name: 'Forbidden',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"zRulSuOqmo","description":"v","details":["aAAru"]}}',
        name: 'Not Found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"ewOUzaqRxb","description":"srDlAgWhqAHF","details":["JetYGbX"]}}',
        name: 'Internal Server Error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'createProductLabel',
    endpoint: 'labels/product/{param}',
    method: 'post',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 204,
        body: '""',
        name: 'Label created successfully.',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"rFePEssrCF","description":"LLw","details":["xuglnEyoTiaSid"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"DjuWHr","description":"rCeWUCCOkBrYMT","details":["sfiTv"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"to","description":"vusrJBDIAu","details":["TbdfwKsEmppXpyJ"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getLabelsCollection',
    endpoint: 'labels',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"pagination":{"requestedPage":2658,"requestedSize":61959,"retrievedResults":42039,"totalResults":36935,"nextPage":"Q","previousPage":"NfXCXCiGA"},"changes":[{"labelId":49924,"date":"VsuReq","time":"NGSwXFGZ","amount":0.07}]}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"o","description":"VzsbZjEm","details":["rISfED"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"DXMKHrNdBNM","description":"gUvSqu","details":["xefvpZlBDqiOtL"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"I","description":"tKWpLWqH","details":["Jly"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'copyLabel',
    endpoint: 'labels/copy/{param}',
    method: 'post',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 204,
        body: '""',
        name: 'Label copied successfully.',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"VcXvTkPw","description":"IQR","details":["tKmAqi"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"PU","description":"MpbJvmJzRl","details":["PcrNgkmbyWLlvk"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"TFjNvP","description":"rEBY","details":["mH"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'cancelLabel',
    endpoint: 'labels/cancel/{param}',
    method: 'post',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 204,
        body: '""',
        name: 'Label cancelled successfully.',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"XZ","description":"c","details":["MhOntKXkWsscqnQ"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"OarclqE","description":"bsMPSmn","details":["MphQolxif"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"M","description":"AAm","details":["HPV"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'adjustLabel',
    endpoint: 'labels/adjust',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 204,
        body: '""',
        name: 'Label successfully adjusted.',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"eIbuxUJMaEIBe","description":"sjRxUM","details":["lJuAD"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"WruWvbCBywMh","description":"QZViwYDQ","details":["FYg"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"WzVw","description":"bZiKWtHekOd","details":["kl"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'login',
    endpoint: 'auth/login',
    method: 'post',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 204,
        body: '""',
        name: 'Successful login',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"bocSBqWUhmDMBp","description":"TqYoCWcHhDK","details":["JYM"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"QcB","description":"BcGCLdjZFJ","details":["gm"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"t","description":"dSFeVwsJ","details":["Duw"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'getScaleParameters',
    endpoint: 'parameters',
    method: 'get',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"waitingTime":75612,"maxLabels":73689,"activityAutoService":55117,"fruitRemoveTime":59354,"midContainer":78132,"smallContainer":13952,"paper":41313}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"AaCSVGATXC","description":"DnWrMsbNPRmRT","details":["UZoNCGe"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"qjArPzch","description":"FlSYoJbaLC","details":["IVumTTe"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"RRAoCLTtFxcYkFN","description":"nW","details":["hhQTJ"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
  {
    id: 0,
    name: 'updateScaleParameters',
    endpoint: 'parameters',
    method: 'put',
    enabled: true,
    isFolder: false,
    order: 0,
    tag: 'config',
    responses: [
      {
        id: 0,
        status: 200,
        body: '{"waitingTime":54291,"maxLabels":56250,"activityAutoService":64667,"fruitRemoveTime":60387,"midContainer":54310,"smallContainer":64039,"paper":82122}',
        name: 'OK',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 400,
        body: '{"error":{"code":"CiDtseDHd","description":"vLmRM","details":["OJ"]}}',
        name: 'Default bad request',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 404,
        body: '{"error":{"code":"NeVJt","description":"BM","details":["QKSZk"]}}',
        name: 'Default not found',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
      {
        id: 0,
        status: 500,
        body: '{"error":{"code":"t","description":"CElYY","details":["JXE"]}}',
        name: 'Default internal server error',
        isFile: false,
        enabled: true,
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
            responseId: 0,
          },
        ],
        routeId: 0,
      },
    ],
    parentFolderId: null,
  },
]
